spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #url: jdbc:p6spy:mysql://192.168.1.101:3306/MP?useSSL=false&serverTimeZone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://192.168.1.101:3306/MP?useSSL=false&serverTimeZone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root



logging:
  level:
    root: warn
    com.yanglf.mp.mapper: trace
  pattern:
    console: '%p%m%n'


mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1